[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
bytecode_hash = 'none'
fs_permissions = [{ access = "read", path = "./node_modules"},{ access = "read", path = "./out"}]